### ISSUE TITLE
Not working on neovim 0.9 + 

### ISSUE THREAD

**Issue by saifulapm** [krivahtoo/silicon.nvim#35]
Hello, On neovim nighty, It's not working. Just cashing neovim.  
<img width="932" alt="Screenshot 2023-03-22 at 6 47 42 AM" src="https://user-images.githubusercontent.com/3833316/226773483-e6cc37ef-d7b7-43c9-b2b1-7998719afcc9.png">

**Comment by krivahtoo** [comment]
@cschmatzler Is there an error message on crash?

**Comment by saifulapm** [comment]
No error. Just exit Neovim.

**Comment by saifulapm** [comment]
Yes. And If I don't lazyload Silicon.nvim, then It don't allow to enter neovim. Exit on start.

**Comment by bezlant** [comment]
It happened to me as well

**Comment by krivahtoo** [comment]
Yeah, I just updated my nightly and it seems to be broken on the latest `nightly`

**Comment by krivahtoo** [comment]
8bbcd5b should fix this lmk if not

**Comment by chris-av** [comment]
@krivahtoo didn't appear to fix it for me. I have `8bbcd5b` in my git history for the repo. Currently using nvim 0.9.0 and on 2016 Macbook Pro. I updated neovim today and that's how I found this bug. 

Similar behavior as the others: running `nvim .` shows blank screen and then it just exits. No errors printed on the screen. Happens when I `require('silicon')`. 

The regular `silicon` command works on my terminal. I made sure to update it to the latest version.

**Comment by chris-av** [comment]
@bezlant Dunno if this helps, but I got mine to work by doing the following: 

1. comment out the silicon package from your packer install.
2. purge it from your package manager, in my case, `:PackerClean`
3. uncomment out the line from your package manager. Reinstall fresh. This time, I built from source ("install.sh build")

Just checked and it works for me now.

**Comment by Feel-ix-343** [comment]
Doesn't work still

**Comment by bezlant** [comment]
@chris-av thank you, unfortunately didn't help.

**Comment by krivahtoo** [comment]
I have been quite busy lately. I will work on this as soon as I can.

**Comment by michaelrommel** [comment]
Interestingly enough I experimented with Emoji fonts today, on the 0.9.0 version on macOS Ventura.
With
```
font = 'VictorMono Nerd Font=34; Noto Color Emoji'
```
the image is generated, but no emojis show. With
```
font = 'VictorMono Nerd Font=34; Apple Color Emoji'
```
neovim crashes. I do not know whether this helps in narrowing down the issue.

**Comment by michaelrommel** [comment]
Hi,
as I was having trouble using the rust binding and was having crashes, I looked at an alternative. The standalone silicon tool worked for me on all platforms that I am using, so I thought about using that as external call.

I created a pure lua plugin, that covers the standard funtionality and also took inspiration from your idea of `gobbling`. 

If you are interested, the plugin lives here: https://github.com/michaelrommel/nvim-silicon 

Thank you for your inspiration for this inspiration.

  Michael.

**Comment by krivahtoo** [comment]
This should be fixed via 06a4549e05726e731b00a25b567e932189e5d65f

**Comment by herschel-ma** [comment]
I encounted some questions. 
os：win 10, 
nvim: 0.9.4.

I can't even run install.sh with nvim-oxi 0.3.0, so I forked this repo and updated it to version 4, and changed function
`image.write_to` first param in clipboard.rs so that I can compile it.

But when I added `require('silicon')` in my config and restarted nvim, it quits immediately, without any messages as same as before.

Does this plugin support windows os?
